// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_knn_umap_cpp
NumericMatrix fast_knn_umap_cpp(IntegerMatrix indices, NumericMatrix distances, int n_components, int n_epochs, double min_dist, double spread, double local_connectivity, double set_op_mix_ratio, int negative_sample_rate, double learning_rate, double curve_a, double curve_b, double repulsion_strength, std::string mode, std::string init, std::string init_sdev_mode, double init_sdev_value, bool prune_epochs, int spectral_n_iter, int seed, bool verbose);
RcppExport SEXP _fastknnumap_fast_knn_umap_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP n_componentsSEXP, SEXP n_epochsSEXP, SEXP min_distSEXP, SEXP spreadSEXP, SEXP local_connectivitySEXP, SEXP set_op_mix_ratioSEXP, SEXP negative_sample_rateSEXP, SEXP learning_rateSEXP, SEXP curve_aSEXP, SEXP curve_bSEXP, SEXP repulsion_strengthSEXP, SEXP modeSEXP, SEXP initSEXP, SEXP init_sdev_modeSEXP, SEXP init_sdev_valueSEXP, SEXP prune_epochsSEXP, SEXP spectral_n_iterSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< int >::type n_components(n_componentsSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< double >::type min_dist(min_distSEXP);
    Rcpp::traits::input_parameter< double >::type spread(spreadSEXP);
    Rcpp::traits::input_parameter< double >::type local_connectivity(local_connectivitySEXP);
    Rcpp::traits::input_parameter< double >::type set_op_mix_ratio(set_op_mix_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type negative_sample_rate(negative_sample_rateSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< double >::type curve_a(curve_aSEXP);
    Rcpp::traits::input_parameter< double >::type curve_b(curve_bSEXP);
    Rcpp::traits::input_parameter< double >::type repulsion_strength(repulsion_strengthSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< std::string >::type init(initSEXP);
    Rcpp::traits::input_parameter< std::string >::type init_sdev_mode(init_sdev_modeSEXP);
    Rcpp::traits::input_parameter< double >::type init_sdev_value(init_sdev_valueSEXP);
    Rcpp::traits::input_parameter< bool >::type prune_epochs(prune_epochsSEXP);
    Rcpp::traits::input_parameter< int >::type spectral_n_iter(spectral_n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_knn_umap_cpp(indices, distances, n_components, n_epochs, min_dist, spread, local_connectivity, set_op_mix_ratio, negative_sample_rate, learning_rate, curve_a, curve_b, repulsion_strength, mode, init, init_sdev_mode, init_sdev_value, prune_epochs, spectral_n_iter, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// knn_objective_embed_cpp
NumericMatrix knn_objective_embed_cpp(IntegerMatrix indices, NumericMatrix distances, std::string objective, NumericMatrix init_embedding, bool use_init, int n_components, int n_epochs, int negative_sample_rate, double learning_rate, int n_threads, int seed, bool verbose);
RcppExport SEXP _fastknnumap_knn_objective_embed_cpp(SEXP indicesSEXP, SEXP distancesSEXP, SEXP objectiveSEXP, SEXP init_embeddingSEXP, SEXP use_initSEXP, SEXP n_componentsSEXP, SEXP n_epochsSEXP, SEXP negative_sample_rateSEXP, SEXP learning_rateSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type indices(indicesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< std::string >::type objective(objectiveSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type init_embedding(init_embeddingSEXP);
    Rcpp::traits::input_parameter< bool >::type use_init(use_initSEXP);
    Rcpp::traits::input_parameter< int >::type n_components(n_componentsSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< int >::type negative_sample_rate(negative_sample_rateSEXP);
    Rcpp::traits::input_parameter< double >::type learning_rate(learning_rateSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_objective_embed_cpp(indices, distances, objective, init_embedding, use_init, n_components, n_epochs, negative_sample_rate, learning_rate, n_threads, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}
// nn_cpp
List nn_cpp(NumericMatrix data, NumericMatrix points, int k, std::string method, bool square, bool sorted, double p, bool parallel, int cores);
RcppExport SEXP _fastknnumap_nn_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP methodSEXP, SEXP squareSEXP, SEXP sortedSEXP, SEXP pSEXP, SEXP parallelSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    Rcpp::traits::input_parameter< bool >::type sorted(sortedSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cpp(data, points, k, method, square, sorted, p, parallel, cores));
    return rcpp_result_gen;
END_RCPP
}
// cuda_available_cpp
bool cuda_available_cpp();
RcppExport SEXP _fastknnumap_cuda_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cuda_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// nn_cuda_cpp
List nn_cuda_cpp(NumericMatrix data, NumericMatrix points, int k, bool square);
RcppExport SEXP _fastknnumap_nn_cuda_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP squareSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_cuda_cpp(data, points, k, square));
    return rcpp_result_gen;
END_RCPP
}
// metal_available_cpp
bool metal_available_cpp();
RcppExport SEXP _fastknnumap_metal_available_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(metal_available_cpp());
    return rcpp_result_gen;
END_RCPP
}
// nn_metal_cpp
List nn_metal_cpp(NumericMatrix data, NumericMatrix points, int k, bool square);
RcppExport SEXP _fastknnumap_nn_metal_cpp(SEXP dataSEXP, SEXP pointsSEXP, SEXP kSEXP, SEXP squareSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type points(pointsSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type square(squareSEXP);
    rcpp_result_gen = Rcpp::wrap(nn_metal_cpp(data, points, k, square));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastknnumap_fast_knn_umap_cpp", (DL_FUNC) &_fastknnumap_fast_knn_umap_cpp, 21},
    {"_fastknnumap_knn_objective_embed_cpp", (DL_FUNC) &_fastknnumap_knn_objective_embed_cpp, 12},
    {"_fastknnumap_nn_cpp", (DL_FUNC) &_fastknnumap_nn_cpp, 9},
    {"_fastknnumap_cuda_available_cpp", (DL_FUNC) &_fastknnumap_cuda_available_cpp, 0},
    {"_fastknnumap_nn_cuda_cpp", (DL_FUNC) &_fastknnumap_nn_cuda_cpp, 4},
    {"_fastknnumap_metal_available_cpp", (DL_FUNC) &_fastknnumap_metal_available_cpp, 0},
    {"_fastknnumap_nn_metal_cpp", (DL_FUNC) &_fastknnumap_nn_metal_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastknnumap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
