# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_knn_umap_cpp <- function(indices, distances, n_components, n_epochs, min_dist, spread, local_connectivity, set_op_mix_ratio, negative_sample_rate, learning_rate, curve_a, curve_b, repulsion_strength, mode, init, init_sdev_mode, init_sdev_value, prune_epochs, spectral_n_iter, seed, verbose) {
    .Call(`_fastknnumap_fast_knn_umap_cpp`, indices, distances, n_components, n_epochs, min_dist, spread, local_connectivity, set_op_mix_ratio, negative_sample_rate, learning_rate, curve_a, curve_b, repulsion_strength, mode, init, init_sdev_mode, init_sdev_value, prune_epochs, spectral_n_iter, seed, verbose)
}

knn_objective_embed_cpp <- function(indices, distances, objective, init_embedding, use_init, n_components, n_epochs, negative_sample_rate, learning_rate, n_threads, seed, verbose) {
    .Call(`_fastknnumap_knn_objective_embed_cpp`, indices, distances, objective, init_embedding, use_init, n_components, n_epochs, negative_sample_rate, learning_rate, n_threads, seed, verbose)
}

