# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

embedding_cuda_available_cpp <- function() {
    .Call(`_fastEmbedR_embedding_cuda_available_cpp`)
}

spectral_knn_init_cuda_cpp <- function(indices, distances, n_components, spectral_n_iter, seed) {
    .Call(`_fastEmbedR_spectral_knn_init_cuda_cpp`, indices, distances, n_components, spectral_n_iter, seed)
}

knn_embed_cuda_cpp <- function(indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed) {
    .Call(`_fastEmbedR_knn_embed_cuda_cpp`, indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed)
}

knn_umap_cuda_fused_cpp <- function(indices, distances, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode) {
    .Call(`_fastEmbedR_knn_umap_cuda_fused_cpp`, indices, distances, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode)
}

umap_cuda_graph_dump_cpp <- function(indices, distances) {
    .Call(`_fastEmbedR_umap_cuda_graph_dump_cpp`, indices, distances)
}

umap_cuda_optimize_coo_cpp <- function(heads, tails, weights, epochs_per_sample, init, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, optimizer_mode) {
    .Call(`_fastEmbedR_umap_cuda_optimize_coo_cpp`, heads, tails, weights, epochs_per_sample, init, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, optimizer_mode)
}

knn_tsne_exact_cuda_cpp <- function(indices, distances, init, n_epochs, perplexity, learning_rate, stop_lying_iter, mom_switch_iter, momentum, final_momentum, exaggeration_factor, seed) {
    .Call(`_fastEmbedR_knn_tsne_exact_cuda_cpp`, indices, distances, init, n_epochs, perplexity, learning_rate, stop_lying_iter, mom_switch_iter, momentum, final_momentum, exaggeration_factor, seed)
}

knn_tsne_opentsne_cuda_cpp <- function(indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_cuda_cpp`, indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs)
}

standardize_cuda_cpp <- function(data) {
    .Call(`_fastEmbedR_standardize_cuda_cpp`, data)
}

project_embedding_knn_cuda_cpp <- function(reference_layout, projection_indices, projection_distances) {
    .Call(`_fastEmbedR_project_embedding_knn_cuda_cpp`, reference_layout, projection_indices, projection_distances)
}

interpolate_landmark_layout_cuda_cpp <- function(landmark_layout, landmark_indices, projection_indices, projection_distances, n) {
    .Call(`_fastEmbedR_interpolate_landmark_layout_cuda_cpp`, landmark_layout, landmark_indices, projection_indices, projection_distances, n)
}

landmark_project_interpolate_knn_confidence_cuda_cpp <- function(landmark_data, query_data, landmark_layout, landmark_indices, k) {
    .Call(`_fastEmbedR_landmark_project_interpolate_knn_confidence_cuda_cpp`, landmark_data, query_data, landmark_layout, landmark_indices, k)
}

knn_structure_score_cuda_cpp <- function(layout, indices, keep, preserve_k, labels, n_label_levels) {
    .Call(`_fastEmbedR_knn_structure_score_cuda_cpp`, layout, indices, keep, preserve_k, labels, n_label_levels)
}

silhouette_score_cuda_cpp <- function(layout, labels, n_label_levels) {
    .Call(`_fastEmbedR_silhouette_score_cuda_cpp`, layout, labels, n_label_levels)
}

rsvd_multiply_cuda_cpp <- function(left, right, transpose_left) {
    .Call(`_fastEmbedR_rsvd_multiply_cuda_cpp`, left, right, transpose_left)
}

embedding_metal_available_cpp <- function() {
    .Call(`_fastEmbedR_embedding_metal_available_cpp`)
}

spectral_knn_init_metal_cpp <- function(indices, distances, n_components, spectral_n_iter, seed) {
    .Call(`_fastEmbedR_spectral_knn_init_metal_cpp`, indices, distances, n_components, spectral_n_iter, seed)
}

standardize_metal_cpp <- function(data) {
    .Call(`_fastEmbedR_standardize_metal_cpp`, data)
}

project_embedding_knn_metal_cpp <- function(reference_layout, projection_indices, projection_distances) {
    .Call(`_fastEmbedR_project_embedding_knn_metal_cpp`, reference_layout, projection_indices, projection_distances)
}

project_embedding_affine_metal_cpp <- function(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5) {
    .Call(`_fastEmbedR_project_embedding_affine_metal_cpp`, reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation)
}

interpolate_landmark_layout_metal_cpp <- function(landmark_layout, landmark_indices, projection_indices, projection_distances, n) {
    .Call(`_fastEmbedR_interpolate_landmark_layout_metal_cpp`, landmark_layout, landmark_indices, projection_indices, projection_distances, n)
}

landmark_project_interpolate_metal_cpp <- function(landmark_data, query_data, landmark_layout, landmark_indices, k) {
    .Call(`_fastEmbedR_landmark_project_interpolate_metal_cpp`, landmark_data, query_data, landmark_layout, landmark_indices, k)
}

landmark_project_interpolate_knn_confidence_metal_cpp <- function(landmark_data, query_data, landmark_layout, landmark_indices, k) {
    .Call(`_fastEmbedR_landmark_project_interpolate_knn_confidence_metal_cpp`, landmark_data, query_data, landmark_layout, landmark_indices, k)
}

knn_structure_score_metal_cpp <- function(layout, indices, keep, preserve_k, labels, n_label_levels) {
    .Call(`_fastEmbedR_knn_structure_score_metal_cpp`, layout, indices, keep, preserve_k, labels, n_label_levels)
}

silhouette_score_metal_cpp <- function(layout, labels, n_label_levels) {
    .Call(`_fastEmbedR_silhouette_score_metal_cpp`, layout, labels, n_label_levels)
}

knn_embed_metal_cpp <- function(indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed) {
    .Call(`_fastEmbedR_knn_embed_metal_cpp`, indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed)
}

knn_embed_metal_csr_cpp <- function(offsets, neighbors, weights, init, n_epochs, negative_sample_rate, learning_rate, min_dist, max_weight, repulsion_strength, seed, sampler_mode = 0L) {
    .Call(`_fastEmbedR_knn_embed_metal_csr_cpp`, offsets, neighbors, weights, init, n_epochs, negative_sample_rate, learning_rate, min_dist, max_weight, repulsion_strength, seed, sampler_mode)
}

knn_umap_refine_rows_metal_cpp <- function(indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, seed) {
    .Call(`_fastEmbedR_knn_umap_refine_rows_metal_cpp`, indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, seed)
}

rsvd_multiply_metal_cpp <- function(left, right, transpose_left) {
    .Call(`_fastEmbedR_rsvd_multiply_metal_cpp`, left, right, transpose_left)
}

transform_tsne_metal_cpp <- function(reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed) {
    .Call(`_fastEmbedR_transform_tsne_metal_cpp`, reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed)
}

knn_tsne_opentsne_metal_cpp <- function(indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_metal_cpp`, indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs)
}

metal_fft512_stockham_diagnostic_cpp <- function(seed = 1L, inverse = FALSE, n_checks = 8L) {
    .Call(`_fastEmbedR_metal_fft512_stockham_diagnostic_cpp`, seed, inverse, n_checks)
}

metal_mpsgraph_fft_diagnostic_cpp <- function(fft_size = 512L, seed = 1L, n_repeats = 5L) {
    .Call(`_fastEmbedR_metal_mpsgraph_fft_diagnostic_cpp`, fft_size, seed, n_repeats)
}

metal_mpsgraph_convolution_diagnostic_cpp <- function(fft_size = 512L, seed = 1L, n_repeats = 5L) {
    .Call(`_fastEmbedR_metal_mpsgraph_convolution_diagnostic_cpp`, fft_size, seed, n_repeats)
}

standardize_cpu_cpp <- function(data) {
    .Call(`_fastEmbedR_standardize_cpu_cpp`, data)
}

strip_self_neighbors_cpp <- function(indices, distances) {
    .Call(`_fastEmbedR_strip_self_neighbors_cpp`, indices, distances)
}

strip_self_neighbors_float_cpp <- function(indices, distances) {
    .Call(`_fastEmbedR_strip_self_neighbors_float_cpp`, indices, distances)
}

validate_projection_knn_cpp <- function(indices, distances, n_reference, k) {
    .Call(`_fastEmbedR_validate_projection_knn_cpp`, indices, distances, n_reference, k)
}

mean_neighbor_rank_error_cpp <- function(high_indices, embed_indices, k) {
    .Call(`_fastEmbedR_mean_neighbor_rank_error_cpp`, high_indices, embed_indices, k)
}

knn_recall_cpp <- function(approx_indices, exact_indices, k) {
    .Call(`_fastEmbedR_knn_recall_cpp`, approx_indices, exact_indices, k)
}

majority_vote_knn_labels_cpp <- function(embed_indices, labels, k, n_label_levels) {
    .Call(`_fastEmbedR_majority_vote_knn_labels_cpp`, embed_indices, labels, k, n_label_levels)
}

batch_entropy_cpp <- function(embed_indices, batch, k, n_batch_levels) {
    .Call(`_fastEmbedR_batch_entropy_cpp`, embed_indices, batch, k, n_batch_levels)
}

sampled_pair_distances_cpp <- function(x, a, b, n_threads) {
    .Call(`_fastEmbedR_sampled_pair_distances_cpp`, x, a, b, n_threads)
}

knn_structure_score_cpp <- function(layout, indices, keep, preserve_k, labels, n_label_levels) {
    .Call(`_fastEmbedR_knn_structure_score_cpp`, layout, indices, keep, preserve_k, labels, n_label_levels)
}

silhouette_score_cpp <- function(layout, labels) {
    .Call(`_fastEmbedR_silhouette_score_cpp`, layout, labels)
}

interpolate_landmark_layout_cpp <- function(landmark_layout, landmark_indices, projection_indices, projection_distances, n) {
    .Call(`_fastEmbedR_interpolate_landmark_layout_cpp`, landmark_layout, landmark_indices, projection_indices, projection_distances, n)
}

select_low_confidence_rows_cpp <- function(confidence, landmark_indices, fraction) {
    .Call(`_fastEmbedR_select_low_confidence_rows_cpp`, confidence, landmark_indices, fraction)
}

project_embedding_knn_cpp <- function(reference_layout, projection_indices, projection_distances) {
    .Call(`_fastEmbedR_project_embedding_knn_cpp`, reference_layout, projection_indices, projection_distances)
}

project_embedding_affine_cpp <- function(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5) {
    .Call(`_fastEmbedR_project_embedding_affine_cpp`, reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation)
}

project_embedding_affine_parallel_cpp <- function(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5, n_threads = 1L) {
    .Call(`_fastEmbedR_project_embedding_affine_parallel_cpp`, reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation, n_threads)
}

knn_connectivity_range_cpp <- function(indices, col_start, n_cols) {
    .Call(`_fastEmbedR_knn_connectivity_range_cpp`, indices, col_start, n_cols)
}

knn_connectivity_cpp <- function(indices) {
    .Call(`_fastEmbedR_knn_connectivity_cpp`, indices)
}

umap_graph_csr_cpp <- function(indices, distances, col_start, n_cols, edge_budget, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_cpp`, indices, distances, col_start, n_cols, edge_budget, n_threads)
}

umap_graph_csr_float_cpp <- function(indices, distances, col_start, n_cols, edge_budget, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_float_cpp`, indices, distances, col_start, n_cols, edge_budget, n_threads)
}

umap_graph_csr_cuda_like_cpp <- function(indices, distances, col_start, n_cols, edge_budget, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_cuda_like_cpp`, indices, distances, col_start, n_cols, edge_budget, n_threads)
}

umap_graph_csr_binary_union_cpp <- function(indices, col_start, n_cols, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_binary_union_cpp`, indices, col_start, n_cols, n_threads)
}

fast_knn_umap_range_cpp <- function(indices, distances, col_start, n_cols, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_range_cpp`, indices, distances, col_start, n_cols, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose)
}

fast_knn_umap_cpp <- function(indices, distances, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_cpp`, indices, distances, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose)
}

umap_cuda_diffusion_init_csr_cpp <- function(offsets, neighbors, weights, spectral_n_iter, n_threads, seed) {
    .Call(`_fastEmbedR_umap_cuda_diffusion_init_csr_cpp`, offsets, neighbors, weights, spectral_n_iter, n_threads, seed)
}

fast_knn_umap_csr_init_cpp <- function(offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_init_cpp`, offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

fast_knn_umap_csr_atomic_cpp <- function(offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_atomic_cpp`, offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

fast_knn_umap_csr_clean_atomic_cpp <- function(offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, decay_mode, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_clean_atomic_cpp`, offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, decay_mode, verbose)
}

fast_knn_umap_coo_replay_cpp <- function(heads, tails, weights, epochs_per_sample, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, sanitize_each_epoch, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_coo_replay_cpp`, heads, tails, weights, epochs_per_sample, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, sanitize_each_epoch, verbose)
}

knn_umap_refine_range_cpp <- function(indices, distances, init_embedding, col_start, n_cols, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_range_cpp`, indices, distances, init_embedding, col_start, n_cols, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

knn_umap_refine_cpp <- function(indices, distances, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_cpp`, indices, distances, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

knn_umap_refine_masked_cpp <- function(indices, distances, init_embedding, update_rows, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_masked_cpp`, indices, distances, init_embedding, update_rows, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

knn_umap_refine_rows_cpp <- function(indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_rows_cpp`, indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

fast_knn_umap_csr_cpp <- function(offsets, neighbors, weights, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_cpp`, offsets, neighbors, weights, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose)
}

umap_auto_parameters_cpp <- function(distances, n_neighbors, backend) {
    .Call(`_fastEmbedR_umap_auto_parameters_cpp`, distances, n_neighbors, backend)
}

tsne_auto_parameters_cpp <- function(n, k, perplexity, perplexity_missing, backend, negative_gradient_method) {
    .Call(`_fastEmbedR_tsne_auto_parameters_cpp`, n, k, perplexity, perplexity_missing, backend, negative_gradient_method)
}

knn_tsne_opentsne_cpp <- function(indices, distances, y_init, init, n_components, perplexity, theta, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, n_threads, seed, verbose, record_costs, auto_config, auto_iter_end) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_cpp`, indices, distances, y_init, init, n_components, perplexity, theta, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, n_threads, seed, verbose, record_costs, auto_config, auto_iter_end)
}

opentsne_cpu_trace_cpp <- function(indices, distances, y_init, perplexity, n_iter, early_exaggeration, learning_rate, learning_rate_auto, momentum, min_gain, max_step_norm, n_threads) {
    .Call(`_fastEmbedR_opentsne_cpu_trace_cpp`, indices, distances, y_init, perplexity, n_iter, early_exaggeration, learning_rate, learning_rate_auto, momentum, min_gain, max_step_norm, n_threads)
}

transform_tsne_cpp <- function(reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_transform_tsne_cpp`, reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, n_threads, seed, verbose)
}

