# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastembedr_build_config_cpp <- function() {
    .Call(`_fastEmbedR_fastembedr_build_config_cpp`)
}

embedding_cuda_available_cpp <- function() {
    .Call(`_fastEmbedR_embedding_cuda_available_cpp`)
}

spectral_knn_init_cuda_cpp <- function(indices, distances, n_components, spectral_n_iter, seed) {
    .Call(`_fastEmbedR_spectral_knn_init_cuda_cpp`, indices, distances, n_components, spectral_n_iter, seed)
}

knn_embed_cuda_cpp <- function(indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed) {
    .Call(`_fastEmbedR_knn_embed_cuda_cpp`, indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed)
}

knn_umap_cuda_fused_cpp <- function(indices, distances, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode, n_components = 2L, binary_graph = FALSE) {
    .Call(`_fastEmbedR_knn_umap_cuda_fused_cpp`, indices, distances, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode, n_components, binary_graph)
}

knn_umap_cuda_fused_float_cpp <- function(indices, distances, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode, n_components = 2L, binary_graph = FALSE) {
    .Call(`_fastEmbedR_knn_umap_cuda_fused_float_cpp`, indices, distances, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode, n_components, binary_graph)
}

knn_umap_cuda_fused_gpu_cpp <- function(gpu_knn, requested_k, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode, binary_graph, n_components = 2L) {
    .Call(`_fastEmbedR_knn_umap_cuda_fused_gpu_cpp`, gpu_knn, requested_k, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, spectral_n_iter, seed, optimizer_mode, binary_graph, n_components)
}

umap_cuda_graph_dump_cpp <- function(indices, distances) {
    .Call(`_fastEmbedR_umap_cuda_graph_dump_cpp`, indices, distances)
}

umap_cuda_optimize_coo_cpp <- function(heads, tails, weights, epochs_per_sample, init, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, optimizer_mode) {
    .Call(`_fastEmbedR_umap_cuda_optimize_coo_cpp`, heads, tails, weights, epochs_per_sample, init, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, optimizer_mode)
}

umap_cuda_optimize_csr_cpp <- function(offsets, neighbors, weights, epochs_per_sample, init, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, optimizer_mode) {
    .Call(`_fastEmbedR_umap_cuda_optimize_csr_cpp`, offsets, neighbors, weights, epochs_per_sample, init, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, optimizer_mode)
}

knn_tsne_opentsne_cuda_cpp <- function(indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_cuda_cpp`, indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs)
}

knn_tsne_opentsne_cuda_float_cpp <- function(indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_cuda_float_cpp`, indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs)
}

knn_tsne_opentsne_cuda_gpu_cpp <- function(gpu_knn, requested_k, y_init, init, pca_init_data, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_cuda_gpu_cpp`, gpu_knn, requested_k, y_init, init, pca_init_data, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs)
}

standardize_cuda_cpp <- function(data) {
    .Call(`_fastEmbedR_standardize_cuda_cpp`, data)
}

project_embedding_knn_cuda_cpp <- function(reference_layout, projection_indices, projection_distances) {
    .Call(`_fastEmbedR_project_embedding_knn_cuda_cpp`, reference_layout, projection_indices, projection_distances)
}

massive_cuda_projector_create_cpp <- function(layout, k, capacity) {
    .Call(`_fastEmbedR_massive_cuda_projector_create_cpp`, layout, k, capacity)
}

massive_cuda_projector_batch_cpp <- function(pointer, indices, distances) {
    .Call(`_fastEmbedR_massive_cuda_projector_batch_cpp`, pointer, indices, distances)
}

massive_cuda_projector_release_cpp <- function(pointer) {
    invisible(.Call(`_fastEmbedR_massive_cuda_projector_release_cpp`, pointer))
}

interpolate_landmark_layout_cuda_cpp <- function(landmark_layout, landmark_indices, projection_indices, projection_distances, n) {
    .Call(`_fastEmbedR_interpolate_landmark_layout_cuda_cpp`, landmark_layout, landmark_indices, projection_indices, projection_distances, n)
}

landmark_project_interpolate_knn_confidence_cuda_cpp <- function(landmark_data, query_data, landmark_layout, landmark_indices, k) {
    .Call(`_fastEmbedR_landmark_project_interpolate_knn_confidence_cuda_cpp`, landmark_data, query_data, landmark_layout, landmark_indices, k)
}

transform_tsne_cuda_cpp <- function(reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed) {
    .Call(`_fastEmbedR_transform_tsne_cuda_cpp`, reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed)
}

landmark_tsne_transform_cuda_gpu_cpp <- function(gpu_knn, reference_data, query_data, reference_layout, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed, affine_neighbors, affine_ridge, max_extrapolation) {
    .Call(`_fastEmbedR_landmark_tsne_transform_cuda_gpu_cpp`, gpu_knn, reference_data, query_data, reference_layout, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed, affine_neighbors, affine_ridge, max_extrapolation)
}

landmark_umap_project_refine_cuda_gpu_cpp <- function(gpu_knn, reference_data, query_data, reference_layout, landmark_rows, query_rows, n_total, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, seed, affine_neighbors, affine_ridge, max_extrapolation) {
    .Call(`_fastEmbedR_landmark_umap_project_refine_cuda_gpu_cpp`, gpu_knn, reference_data, query_data, reference_layout, landmark_rows, query_rows, n_total, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, seed, affine_neighbors, affine_ridge, max_extrapolation)
}

knn_structure_score_cuda_cpp <- function(layout, indices, keep, preserve_k, labels, n_label_levels) {
    .Call(`_fastEmbedR_knn_structure_score_cuda_cpp`, layout, indices, keep, preserve_k, labels, n_label_levels)
}

silhouette_score_cuda_cpp <- function(layout, labels, n_label_levels) {
    .Call(`_fastEmbedR_silhouette_score_cuda_cpp`, layout, labels, n_label_levels)
}

rsvd_multiply_cuda_cpp <- function(left, right, transpose_left) {
    .Call(`_fastEmbedR_rsvd_multiply_cuda_cpp`, left, right, transpose_left)
}

pca_tsvd_cuda_cpp <- function(data, n_components, center, scale, seed, requested_method, oversample, power) {
    .Call(`_fastEmbedR_pca_tsvd_cuda_cpp`, data, n_components, center, scale, seed, requested_method, oversample, power)
}

embedding_metal_available_cpp <- function() {
    .Call(`_fastEmbedR_embedding_metal_available_cpp`)
}

spectral_knn_init_metal_cpp <- function(indices, distances, n_components, spectral_n_iter, seed) {
    .Call(`_fastEmbedR_spectral_knn_init_metal_cpp`, indices, distances, n_components, spectral_n_iter, seed)
}

standardize_metal_cpp <- function(data) {
    .Call(`_fastEmbedR_standardize_metal_cpp`, data)
}

project_embedding_knn_metal_cpp <- function(reference_layout, projection_indices, projection_distances) {
    .Call(`_fastEmbedR_project_embedding_knn_metal_cpp`, reference_layout, projection_indices, projection_distances)
}

project_embedding_affine_metal_cpp <- function(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5) {
    .Call(`_fastEmbedR_project_embedding_affine_metal_cpp`, reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation)
}

interpolate_landmark_layout_metal_cpp <- function(landmark_layout, landmark_indices, projection_indices, projection_distances, n) {
    .Call(`_fastEmbedR_interpolate_landmark_layout_metal_cpp`, landmark_layout, landmark_indices, projection_indices, projection_distances, n)
}

landmark_project_interpolate_metal_cpp <- function(landmark_data, query_data, landmark_layout, landmark_indices, k) {
    .Call(`_fastEmbedR_landmark_project_interpolate_metal_cpp`, landmark_data, query_data, landmark_layout, landmark_indices, k)
}

landmark_project_interpolate_knn_confidence_metal_cpp <- function(landmark_data, query_data, landmark_layout, landmark_indices, k) {
    .Call(`_fastEmbedR_landmark_project_interpolate_knn_confidence_metal_cpp`, landmark_data, query_data, landmark_layout, landmark_indices, k)
}

knn_structure_score_metal_cpp <- function(layout, indices, keep, preserve_k, labels, n_label_levels) {
    .Call(`_fastEmbedR_knn_structure_score_metal_cpp`, layout, indices, keep, preserve_k, labels, n_label_levels)
}

silhouette_score_metal_cpp <- function(layout, labels, n_label_levels) {
    .Call(`_fastEmbedR_silhouette_score_metal_cpp`, layout, labels, n_label_levels)
}

knn_embed_metal_cpp <- function(indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed) {
    .Call(`_fastEmbedR_knn_embed_metal_cpp`, indices, distances, init, objective, n_epochs, negative_sample_rate, learning_rate, min_dist, seed)
}

knn_embed_metal_csr_cpp <- function(offsets, neighbors, weights, init, n_epochs, negative_sample_rate, learning_rate, min_dist, max_weight, repulsion_strength, seed, sampler_mode = 0L) {
    .Call(`_fastEmbedR_knn_embed_metal_csr_cpp`, offsets, neighbors, weights, init, n_epochs, negative_sample_rate, learning_rate, min_dist, max_weight, repulsion_strength, seed, sampler_mode)
}

knn_umap_refine_rows_metal_cpp <- function(indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, seed) {
    .Call(`_fastEmbedR_knn_umap_refine_rows_metal_cpp`, indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, seed)
}

rsvd_multiply_metal_cpp <- function(left, right, transpose_left) {
    .Call(`_fastEmbedR_rsvd_multiply_metal_cpp`, left, right, transpose_left)
}

pca_tsvd_metal_cpp <- function(data, n_components, center = TRUE, scale = FALSE, seed = 4L, oversample = 16L, power = 1L) {
    .Call(`_fastEmbedR_pca_tsvd_metal_cpp`, data, n_components, center, scale, seed, oversample, power)
}

transform_tsne_metal_cpp <- function(reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed) {
    .Call(`_fastEmbedR_transform_tsne_metal_cpp`, reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, seed)
}

knn_tsne_opentsne_metal_cpp <- function(indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs, auto_config, auto_iter_end) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_metal_cpp`, indices, distances, y_init, init, n_components, perplexity, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, seed, record_costs, auto_config, auto_iter_end)
}

pca_rsvd_cpu_cpp <- function(data, n_components, center, scale, omega, power, n_threads = 1L) {
    .Call(`_fastEmbedR_pca_rsvd_cpu_cpp`, data, n_components, center, scale, omega, power, n_threads)
}

float32_all_finite_cpp <- function(data, n_threads = 0L) {
    .Call(`_fastEmbedR_float32_all_finite_cpp`, data, n_threads)
}

standardize_cpu_cpp <- function(data) {
    .Call(`_fastEmbedR_standardize_cpu_cpp`, data)
}

standardize_float32_cpp <- function(data, n_threads = 0L) {
    .Call(`_fastEmbedR_standardize_float32_cpp`, data, n_threads)
}

split_float32_rows_cpp <- function(data, landmark_rows, query_rows, n_threads = 0L) {
    .Call(`_fastEmbedR_split_float32_rows_cpp`, data, landmark_rows, query_rows, n_threads)
}

landmark_projection_float32_cpp <- function(data, directions, n_direct = 4L, n_threads = 0L) {
    .Call(`_fastEmbedR_landmark_projection_float32_cpp`, data, directions, n_direct, n_threads)
}

strip_self_neighbors_cpp <- function(indices, distances) {
    .Call(`_fastEmbedR_strip_self_neighbors_cpp`, indices, distances)
}

strip_self_neighbors_float_cpp <- function(indices, distances) {
    .Call(`_fastEmbedR_strip_self_neighbors_float_cpp`, indices, distances)
}

validate_projection_knn_cpp <- function(indices, distances, n_reference, k) {
    .Call(`_fastEmbedR_validate_projection_knn_cpp`, indices, distances, n_reference, k)
}

mean_neighbor_rank_error_cpp <- function(high_indices, embed_indices, k) {
    .Call(`_fastEmbedR_mean_neighbor_rank_error_cpp`, high_indices, embed_indices, k)
}

knn_recall_cpp <- function(approx_indices, exact_indices, k) {
    .Call(`_fastEmbedR_knn_recall_cpp`, approx_indices, exact_indices, k)
}

majority_vote_knn_labels_cpp <- function(embed_indices, labels, k, n_label_levels) {
    .Call(`_fastEmbedR_majority_vote_knn_labels_cpp`, embed_indices, labels, k, n_label_levels)
}

batch_entropy_cpp <- function(embed_indices, batch, k, n_batch_levels) {
    .Call(`_fastEmbedR_batch_entropy_cpp`, embed_indices, batch, k, n_batch_levels)
}

sampled_pair_distances_cpp <- function(x, a, b, n_threads) {
    .Call(`_fastEmbedR_sampled_pair_distances_cpp`, x, a, b, n_threads)
}

knn_structure_score_cpp <- function(layout, indices, keep, preserve_k, labels, n_label_levels) {
    .Call(`_fastEmbedR_knn_structure_score_cpp`, layout, indices, keep, preserve_k, labels, n_label_levels)
}

exact_structure_metrics_cpp <- function(high, low, requested_k, n_threads) {
    .Call(`_fastEmbedR_exact_structure_metrics_cpp`, high, low, requested_k, n_threads)
}

silhouette_score_cpp <- function(layout, labels) {
    .Call(`_fastEmbedR_silhouette_score_cpp`, layout, labels)
}

interpolate_landmark_layout_cpp <- function(landmark_layout, landmark_indices, projection_indices, projection_distances, n) {
    .Call(`_fastEmbedR_interpolate_landmark_layout_cpp`, landmark_layout, landmark_indices, projection_indices, projection_distances, n)
}

select_low_confidence_rows_cpp <- function(confidence, landmark_indices, fraction) {
    .Call(`_fastEmbedR_select_low_confidence_rows_cpp`, confidence, landmark_indices, fraction)
}

project_embedding_knn_cpp <- function(reference_layout, projection_indices, projection_distances) {
    .Call(`_fastEmbedR_project_embedding_knn_cpp`, reference_layout, projection_indices, projection_distances)
}

project_embedding_affine_cpp <- function(reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5) {
    .Call(`_fastEmbedR_project_embedding_affine_cpp`, reference_data, query_data, reference_layout, projection_indices, projection_distances, max_neighbors, ridge, max_extrapolation)
}

project_embedding_affine_parallel_cpp <- function(reference_data_sexp, query_data_sexp, reference_layout_sexp, projection_indices, projection_distances_sexp, max_neighbors = 12L, ridge = 1e-3, max_extrapolation = 2.5, n_threads = 1L) {
    .Call(`_fastEmbedR_project_embedding_affine_parallel_cpp`, reference_data_sexp, query_data_sexp, reference_layout_sexp, projection_indices, projection_distances_sexp, max_neighbors, ridge, max_extrapolation, n_threads)
}

knn_connectivity_range_cpp <- function(indices, col_start, n_cols) {
    .Call(`_fastEmbedR_knn_connectivity_range_cpp`, indices, col_start, n_cols)
}

knn_connectivity_cpp <- function(indices) {
    .Call(`_fastEmbedR_knn_connectivity_cpp`, indices)
}

umap_graph_csr_cpp <- function(indices, distances, col_start, n_cols, edge_budget, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_cpp`, indices, distances, col_start, n_cols, edge_budget, n_threads)
}

umap_graph_csr_float_cpp <- function(indices, distances, col_start, n_cols, edge_budget, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_float_cpp`, indices, distances, col_start, n_cols, edge_budget, n_threads)
}

umap_graph_csr_cuda_like_cpp <- function(indices, distances, col_start, n_cols, edge_budget, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_cuda_like_cpp`, indices, distances, col_start, n_cols, edge_budget, n_threads)
}

umap_graph_csr_binary_union_cpp <- function(indices, col_start, n_cols, n_threads) {
    .Call(`_fastEmbedR_umap_graph_csr_binary_union_cpp`, indices, col_start, n_cols, n_threads)
}

fast_knn_umap_range_cpp <- function(indices, distances, col_start, n_cols, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_range_cpp`, indices, distances, col_start, n_cols, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose)
}

fast_knn_umap_cpp <- function(indices, distances, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_cpp`, indices, distances, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose)
}

umap_cuda_diffusion_init_csr_cpp <- function(offsets, neighbors, weights, spectral_n_iter, n_threads, seed) {
    .Call(`_fastEmbedR_umap_cuda_diffusion_init_csr_cpp`, offsets, neighbors, weights, spectral_n_iter, n_threads, seed)
}

fast_knn_umap_csr_init_cpp <- function(offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_init_cpp`, offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

fast_knn_umap_csr_atomic_cpp <- function(offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_atomic_cpp`, offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

fast_knn_umap_csr_clean_atomic_cpp <- function(offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, decay_mode, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_clean_atomic_cpp`, offsets, neighbors, weights, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, decay_mode, verbose)
}

fast_knn_umap_coo_replay_cpp <- function(heads, tails, weights, epochs_per_sample, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, sanitize_each_epoch, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_coo_replay_cpp`, heads, tails, weights, epochs_per_sample, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, sanitize_each_epoch, verbose)
}

knn_umap_refine_range_cpp <- function(indices, distances, init_embedding, col_start, n_cols, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_range_cpp`, indices, distances, init_embedding, col_start, n_cols, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

knn_umap_refine_cpp <- function(indices, distances, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_cpp`, indices, distances, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

knn_umap_refine_masked_cpp <- function(indices, distances, init_embedding, update_rows, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_masked_cpp`, indices, distances, init_embedding, update_rows, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

knn_umap_refine_rows_cpp <- function(indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_knn_umap_refine_rows_cpp`, indices, distances, row_ids, init_embedding, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, n_threads, seed, verbose)
}

fast_knn_umap_csr_cpp <- function(offsets, neighbors, weights, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose) {
    .Call(`_fastEmbedR_fast_knn_umap_csr_cpp`, offsets, neighbors, weights, n_components, n_epochs, min_dist, negative_sample_rate, learning_rate, repulsion_strength, spectral_n_iter, n_threads, init_scale, seed, verbose)
}

umap_auto_parameters_cpp <- function(distances, n_neighbors, backend) {
    .Call(`_fastEmbedR_umap_auto_parameters_cpp`, distances, n_neighbors, backend)
}

fastembedr_graph_from_knn_cpp <- function(indices, distances, weight_type = "snn", mutual = FALSE, prune = 0.0, n_threads = 1L) {
    .Call(`_fastEmbedR_fastembedr_graph_from_knn_cpp`, indices, distances, weight_type, mutual, prune, n_threads)
}

fastembedr_graph_cluster_cpp <- function(from, to, weight, n_vertices, method = "leiden", resolution = 1.0, n_iterations = 10L, n_runs = 1L, seed = 1) {
    .Call(`_fastEmbedR_fastembedr_graph_cluster_cpp`, from, to, weight, n_vertices, method, resolution, n_iterations, n_runs, seed)
}

fastembedr_graph_modularity_cpp <- function(from, to, weight, n_vertices, membership, resolution = 1.0) {
    .Call(`_fastEmbedR_fastembedr_graph_modularity_cpp`, from, to, weight, n_vertices, membership, resolution)
}

graph_clustering_cuda_available_cpp <- function() {
    .Call(`_fastEmbedR_graph_clustering_cuda_available_cpp`)
}

fastembedr_graph_cluster_cuda_cpp <- function(from, to, weight, n_vertices, method = "leiden", resolution = 1.0, n_iterations = 10L, n_runs = 1L, seed = 1) {
    .Call(`_fastEmbedR_fastembedr_graph_cluster_cuda_cpp`, from, to, weight, n_vertices, method, resolution, n_iterations, n_runs, seed)
}

graph_clustering_metal_available_cpp <- function() {
    .Call(`_fastEmbedR_graph_clustering_metal_available_cpp`)
}

graph_clustering_metal_error_cpp <- function() {
    .Call(`_fastEmbedR_graph_clustering_metal_error_cpp`)
}

fastembedr_graph_cluster_metal_cpp <- function(from, to, weight, n_vertices, method = "leiden", resolution = 1.0, n_iterations = 10L, n_runs = 1L, seed = 1) {
    .Call(`_fastEmbedR_fastembedr_graph_cluster_metal_cpp`, from, to, weight, n_vertices, method, resolution, n_iterations, n_runs, seed)
}

massive_merge_knn_shard_cpp <- function(indices_path, distances_path, indices, distances, query_first, shard_first, shard_rows, n_vertices, k, first_shard, n_queries = -1.0, exclude_self = TRUE) {
    invisible(.Call(`_fastEmbedR_massive_merge_knn_shard_cpp`, indices_path, distances_path, indices, distances, query_first, shard_first, shard_rows, n_vertices, k, first_shard, n_queries, exclude_self))
}

massive_reorder_posting_graph_cpp <- function(posting_ids_path, grouped_indices_path, grouped_distances_path, output_indices_path, output_distances_path, n_vertices, k, bucket_rows, read_rows, restart_work) {
    invisible(.Call(`_fastEmbedR_massive_reorder_posting_graph_cpp`, posting_ids_path, grouped_indices_path, grouped_distances_path, output_indices_path, output_distances_path, n_vertices, k, bucket_rows, read_rows, restart_work))
}

massive_file_info_cpp <- function(path, format, rows, columns) {
    .Call(`_fastEmbedR_massive_file_info_cpp`, path, format, rows, columns)
}

massive_disk_available_cpp <- function(output) {
    .Call(`_fastEmbedR_massive_disk_available_cpp`, output)
}

massive_graph_modularity_cpp <- function(offsets_path, indices_path, weights_path, membership_path, n_vertices, n_communities, resolution, chunk_rows, edge_budget) {
    .Call(`_fastEmbedR_massive_graph_modularity_cpp`, offsets_path, indices_path, weights_path, membership_path, n_vertices, n_communities, resolution, chunk_rows, edge_budget)
}

massive_louvain_level_cpp <- function(offsets_path, indices_path, weights_path, n_vertices, output, max_passes, resolution, chunk_rows, edge_budget, seed, contracted, initial_path = "", initial_count = 0L) {
    .Call(`_fastEmbedR_massive_louvain_level_cpp`, offsets_path, indices_path, weights_path, n_vertices, output, max_passes, resolution, chunk_rows, edge_budget, seed, contracted, initial_path, initial_count)
}

massive_leiden_refine_cpp <- function(offsets_path, indices_path, weights_path, parent_path, n_vertices, n_parent, output, resolution, chunk_rows, edge_budget, seed, contracted) {
    .Call(`_fastEmbedR_massive_leiden_refine_cpp`, offsets_path, indices_path, weights_path, parent_path, n_vertices, n_parent, output, resolution, chunk_rows, edge_budget, seed, contracted)
}

massive_reference_buffer_cpp <- function(spec) {
    .Call(`_fastEmbedR_massive_reference_buffer_cpp`, spec)
}

massive_read_rows_cpp <- function(spec, first_row, count, max_bytes, float32 = FALSE) {
    .Call(`_fastEmbedR_massive_read_rows_cpp`, spec, first_row, count, max_bytes, float32)
}

massive_read_knn_rows_cpp <- function(indices_path, distances_path, n_rows, k, n_reference, first_row, count, max_bytes) {
    .Call(`_fastEmbedR_massive_read_knn_rows_cpp`, indices_path, distances_path, n_rows, k, n_reference, first_row, count, max_bytes)
}

massive_validate_graph_cpp <- function(indices_path, distances_path, n_vertices, k, access, kind) {
    .Call(`_fastEmbedR_massive_validate_graph_cpp`, indices_path, distances_path, n_vertices, k, access, kind)
}

massive_graph_storage_cpp <- function(n_vertices, k) {
    .Call(`_fastEmbedR_massive_graph_storage_cpp`, n_vertices, k)
}

massive_umap_global_mean_cpp <- function(indices_path, distances_path, n_vertices, k) {
    .Call(`_fastEmbedR_massive_umap_global_mean_cpp`, indices_path, distances_path, n_vertices, k)
}

massive_umap_global_mean_resume_cpp <- function(indices_path, distances_path, n_vertices, k, completed_rows, sum, progress, checkpoint_every) {
    .Call(`_fastEmbedR_massive_umap_global_mean_resume_cpp`, indices_path, distances_path, n_vertices, k, completed_rows, sum, progress, checkpoint_every)
}

massive_umap_memberships_cpp <- function(indices_path, distances_path, n_vertices, k, output_path, global_mean, start_row = 0, progress = NULL, resume = FALSE, checkpoint_every = 100L, n_threads = 1L) {
    invisible(.Call(`_fastEmbedR_massive_umap_memberships_cpp`, indices_path, distances_path, n_vertices, k, output_path, global_mean, start_row, progress, resume, checkpoint_every, n_threads))
}

massive_symmetrize_graph_cpp <- function(indices_path, values_path, n_vertices, k, output_prefix, memory_limit_bytes, method, perplexity, n_threads, resume, completed_rows, resume_runs, checkpoint_every, progress) {
    .Call(`_fastEmbedR_massive_symmetrize_graph_cpp`, indices_path, values_path, n_vertices, k, output_prefix, memory_limit_bytes, method, perplexity, n_threads, resume, completed_rows, resume_runs, checkpoint_every, progress)
}

massive_contract_louvain_cpp <- function(offsets_path, indices_path, weights_path, membership_path, n_vertices, n_communities, output_path, memory_limit_bytes, chunk_rows, edge_budget, contracted) {
    .Call(`_fastEmbedR_massive_contract_louvain_cpp`, offsets_path, indices_path, weights_path, membership_path, n_vertices, n_communities, output_path, memory_limit_bytes, chunk_rows, edge_budget, contracted)
}

massive_coarse_csr_cpp <- function(input, n_vertices, n_edges, output, memory_limit_bytes) {
    .Call(`_fastEmbedR_massive_coarse_csr_cpp`, input, n_vertices, n_edges, output, memory_limit_bytes)
}

massive_remap_louvain_cpp <- function(labels_path, mapping_path, n_vertices, n_mapping_vertices) {
    invisible(.Call(`_fastEmbedR_massive_remap_louvain_cpp`, labels_path, mapping_path, n_vertices, n_mapping_vertices))
}

massive_read_contracted_cpp <- function(path, n_vertices, n_edges) {
    .Call(`_fastEmbedR_massive_read_contracted_cpp`, path, n_vertices, n_edges)
}

massive_umap_optimize_cpp <- function(offsets_path, indices_path, weights_path, n_vertices, init_path, init_format, dimensions, output, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, chunk_rows, memory_limit_bytes, start_epoch = 0L, positive_done = 0, negative_done = 0, checkpoint_every = 0L, checkpoint_callback = NULL, layout_storage = "memory") {
    .Call(`_fastEmbedR_massive_umap_optimize_cpp`, offsets_path, indices_path, weights_path, n_vertices, init_path, init_format, dimensions, output, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, chunk_rows, memory_limit_bytes, start_epoch, positive_done, negative_done, checkpoint_every, checkpoint_callback, layout_storage)
}

massive_umap_optimize_cuda_cpp <- function(offsets_path, indices_path, weights_path, n_vertices, init_path, init_format, output, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, chunk_rows, edge_capacity, memory_limit_bytes, start_epoch = 0L, checkpoint_every = 0L, checkpoint_callback = NULL, visits_done = 0, dimensions = 2L, layout_storage = "memory") {
    .Call(`_fastEmbedR_massive_umap_optimize_cuda_cpp`, offsets_path, indices_path, weights_path, n_vertices, init_path, init_format, output, n_epochs, negative_sample_rate, learning_rate, min_dist, repulsion_strength, seed, chunk_rows, edge_capacity, memory_limit_bytes, start_epoch, checkpoint_every, checkpoint_callback, visits_done, dimensions, layout_storage)
}

massive_tsne_optimize_cuda_cpp <- function(offsets_path, indices_path, weights_path, access, init_path, output_path, n, dims, early_iter, normal_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, start_iter, state_path, checkpoint_every, checkpoint_callback, edge_capacity) {
    .Call(`_fastEmbedR_massive_tsne_optimize_cuda_cpp`, offsets_path, indices_path, weights_path, access, init_path, output_path, n, dims, early_iter, normal_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, start_iter, state_path, checkpoint_every, checkpoint_callback, edge_capacity)
}

massive_read_graph_edges_cpp <- function(indices_path, distances_path, n_vertices, k, access, first_row, count, max_bytes, kind) {
    .Call(`_fastEmbedR_massive_read_graph_edges_cpp`, indices_path, distances_path, n_vertices, k, access, first_row, count, max_bytes, kind)
}

massive_validate_csr_graph_cpp <- function(offsets_path, indices_path, weights_path, n_vertices) {
    .Call(`_fastEmbedR_massive_validate_csr_graph_cpp`, offsets_path, indices_path, weights_path, n_vertices)
}

massive_read_csr_graph_edges_cpp <- function(offsets_path, indices_path, weights_path, n_vertices, access, first_row, count, max_bytes) {
    .Call(`_fastEmbedR_massive_read_csr_graph_edges_cpp`, offsets_path, indices_path, weights_path, n_vertices, access, first_row, count, max_bytes)
}

massive_exact_graph_batch_cpp <- function(spec, first_row, count, k, reference_chunk, n_threads) {
    .Call(`_fastEmbedR_massive_exact_graph_batch_cpp`, spec, first_row, count, k, reference_chunk, n_threads)
}

massive_exact_reference_batch_cpp <- function(query_spec, reference_spec, first_row, count, k, reference_chunk, n_threads) {
    .Call(`_fastEmbedR_massive_exact_reference_batch_cpp`, query_spec, reference_spec, first_row, count, k, reference_chunk, n_threads)
}

massive_exact_sample_batch_cpp <- function(query_spec, reference_spec, row_ids, k, reference_chunk, n_threads, exclude_self) {
    .Call(`_fastEmbedR_massive_exact_sample_batch_cpp`, query_spec, reference_spec, row_ids, k, reference_chunk, n_threads, exclude_self)
}

massive_vote_landmarks_cpp <- function(indices, distances, landmark_labels, n_threads) {
    .Call(`_fastEmbedR_massive_vote_landmarks_cpp`, indices, distances, landmark_labels, n_threads)
}

massive_read_cluster_rows_cpp <- function(labels_path, confidence_path, n_rows, first_row, count, max_bytes) {
    .Call(`_fastEmbedR_massive_read_cluster_rows_cpp`, labels_path, confidence_path, n_rows, first_row, count, max_bytes)
}

massive_pca_means_cpp <- function(spec, chunk_rows, n_threads, center) {
    .Call(`_fastEmbedR_massive_pca_means_cpp`, spec, chunk_rows, n_threads, center)
}

massive_pca_mean_chunk_cpp <- function(spec, first, rows, n_threads, previous) {
    .Call(`_fastEmbedR_massive_pca_mean_chunk_cpp`, spec, first, rows, n_threads, previous)
}

massive_pca_covariance_cpp <- function(spec, chunk_rows, n_threads, center, saved_means = NULL, completed_rows = 0, saved_cross = NULL, progress = NULL, checkpoint_every = 0L) {
    .Call(`_fastEmbedR_massive_pca_covariance_cpp`, spec, chunk_rows, n_threads, center, saved_means, completed_rows, saved_cross, progress, checkpoint_every)
}

massive_pca_wide_moments_cpp <- function(spec, chunk_rows, n_threads, center, scale) {
    .Call(`_fastEmbedR_massive_pca_wide_moments_cpp`, spec, chunk_rows, n_threads, center, scale)
}

massive_pca_wide_action_cpp <- function(spec, center, scale, basis, chunk_rows, n_threads) {
    .Call(`_fastEmbedR_massive_pca_wide_action_cpp`, spec, center, scale, basis, chunk_rows, n_threads)
}

massive_pca_wide_action_cuda_cpp <- function(spec, center, scale, basis, chunk_rows) {
    .Call(`_fastEmbedR_massive_pca_wide_action_cuda_cpp`, spec, center, scale, basis, chunk_rows)
}

massive_pca_covariance_cuda_cpp <- function(spec, chunk_rows, n_threads, center, saved_means = NULL, completed_rows = 0, saved_cross = NULL, progress = NULL, checkpoint_every = 0L) {
    .Call(`_fastEmbedR_massive_pca_covariance_cuda_cpp`, spec, chunk_rows, n_threads, center, saved_means, completed_rows, saved_cross, progress, checkpoint_every)
}

massive_cuda_memory_cpp <- function() {
    .Call(`_fastEmbedR_massive_cuda_memory_cpp`)
}

massive_cuda_device_count_cpp <- function() {
    .Call(`_fastEmbedR_massive_cuda_device_count_cpp`)
}

massive_cuda_select_cpp <- function(device) {
    .Call(`_fastEmbedR_massive_cuda_select_cpp`, device)
}

massive_concat_word_files_cpp <- function(paths, output, byte_counts, resume = FALSE) {
    invisible(.Call(`_fastEmbedR_massive_concat_word_files_cpp`, paths, output, byte_counts, resume))
}

massive_pca_project_cpp <- function(spec, output, loadings, center, scale, chunk_rows, n_threads, start_row = 0, progress = NULL, resume = FALSE) {
    invisible(.Call(`_fastEmbedR_massive_pca_project_cpp`, spec, output, loadings, center, scale, chunk_rows, n_threads, start_row, progress, resume))
}

massive_pca_project_cuda_cpp <- function(spec, output, loadings, center, scale, chunk_rows, start_row = 0, progress = NULL, resume = FALSE) {
    invisible(.Call(`_fastEmbedR_massive_pca_project_cuda_cpp`, spec, output, loadings, center, scale, chunk_rows, start_row, progress, resume))
}

massive_landmark_sample_cpp <- function(spec, landmarks, seed, chunk_rows, output, method) {
    .Call(`_fastEmbedR_massive_landmark_sample_cpp`, spec, landmarks, seed, chunk_rows, output, method)
}

massive_posting_distant_rows_cpp <- function(spec, centers_r, sample, chunk_rows, workers, candidate_rows = 0L) {
    .Call(`_fastEmbedR_massive_posting_distant_rows_cpp`, spec, centers_r, sample, chunk_rows, workers, candidate_rows)
}

massive_coarse_postings_cpp <- function(spec, centers_r, prefix, chunk_rows, workers, resume_state, checkpoint_callback, checkpoint_every) {
    .Call(`_fastEmbedR_massive_coarse_postings_cpp`, spec, centers_r, prefix, chunk_rows, workers, resume_state, checkpoint_callback, checkpoint_every)
}

massive_posting_search_cpp <- function(query_spec, feature_path, ids_path, offsets_path, centers, first_row, count, k, nprobe, reference_chunk, workers, exclude_self, posting_rows, verbose) {
    .Call(`_fastEmbedR_massive_posting_search_cpp`, query_spec, feature_path, ids_path, offsets_path, centers, first_row, count, k, nprobe, reference_chunk, workers, exclude_self, posting_rows, verbose)
}

native_hnsw_knn_cpp <- function(data, k, n_threads = 1L, metric = "euclidean", target_recall = 0.99) {
    .Call(`_fastEmbedR_native_hnsw_knn_cpp`, data, k, n_threads, metric, target_recall)
}

native_hnsw_query_cpp <- function(data, query, k, n_threads = 1L, metric = "euclidean", target_recall = 0.99) {
    .Call(`_fastEmbedR_native_hnsw_query_cpp`, data, query, k, n_threads, metric, target_recall)
}

native_hnsw_index_build_cpp <- function(data, k, n_threads = 1L, metric = "euclidean", target_recall = 0.99) {
    .Call(`_fastEmbedR_native_hnsw_index_build_cpp`, data, k, n_threads, metric, target_recall)
}

native_hnsw_index_search_cpp <- function(pointer, query, k, n_threads = 1L, ef_search = 0L) {
    .Call(`_fastEmbedR_native_hnsw_index_search_cpp`, pointer, query, k, n_threads, ef_search)
}

native_exact_knn_cpp <- function(data, k, n_threads = 1L, metric = "euclidean", target_recall = 0.99) {
    .Call(`_fastEmbedR_native_exact_knn_cpp`, data, k, n_threads, metric, target_recall)
}

native_exact_query_cpp <- function(data, query, k, n_threads = 1L, metric = "euclidean", target_recall = 0.99) {
    .Call(`_fastEmbedR_native_exact_query_cpp`, data, query, k, n_threads, metric, target_recall)
}

native_exact_index_build_cpp <- function(data) {
    .Call(`_fastEmbedR_native_exact_index_build_cpp`, data)
}

native_exact_index_search_cpp <- function(pointer, query, k, n_threads = 1L) {
    .Call(`_fastEmbedR_native_exact_index_search_cpp`, pointer, query, k, n_threads)
}

native_metal_knn_available_cpp <- function() {
    .Call(`_fastEmbedR_native_metal_knn_available_cpp`)
}

native_metal_knn_cpp <- function(data, k, method = "auto", metric = "euclidean", target_recall = 0.99) {
    .Call(`_fastEmbedR_native_metal_knn_cpp`, data, k, method, metric, target_recall)
}

native_metal_query_knn_cpp <- function(data, query, k, method = "auto", metric = "euclidean", target_recall = 0.99) {
    .Call(`_fastEmbedR_native_metal_query_knn_cpp`, data, query, k, method, metric, target_recall)
}

native_cuda_knn_available_cpp <- function() {
    .Call(`_fastEmbedR_native_cuda_knn_available_cpp`)
}

native_cuda_memory_info_cpp <- function() {
    .Call(`_fastEmbedR_native_cuda_memory_info_cpp`)
}

native_cuda_knn_cpp <- function(data, k, method = "auto", metric = "euclidean", target_recall = 0.99, keep_gpu = TRUE, retain_data = FALSE) {
    .Call(`_fastEmbedR_native_cuda_knn_cpp`, data, k, method, metric, target_recall, keep_gpu, retain_data)
}

native_cuda_query_knn_cpp <- function(data, query, k, method = "auto", metric = "euclidean", target_recall = 0.99, keep_gpu = TRUE) {
    .Call(`_fastEmbedR_native_cuda_query_knn_cpp`, data, query, k, method, metric, target_recall, keep_gpu)
}

native_cuda_knn_to_host_cpp <- function(knn) {
    .Call(`_fastEmbedR_native_cuda_knn_to_host_cpp`, knn)
}

native_cuda_index_build_cpp <- function(data, k, method, target_recall = 0.99) {
    .Call(`_fastEmbedR_native_cuda_index_build_cpp`, data, k, method, target_recall)
}

native_cuda_index_search_cpp <- function(pointer, query, k) {
    .Call(`_fastEmbedR_native_cuda_index_search_cpp`, pointer, query, k)
}

opentsne_kl_diagnostic_cpp <- function(indices, distances, layout, perplexity, n_threads) {
    .Call(`_fastEmbedR_opentsne_kl_diagnostic_cpp`, indices, distances, layout, perplexity, n_threads)
}

opentsne_force_diagnostic_cpp <- function(indices, distances, layout, perplexity, exaggeration, grid_size, n_threads) {
    .Call(`_fastEmbedR_opentsne_force_diagnostic_cpp`, indices, distances, layout, perplexity, exaggeration, grid_size, n_threads)
}

tsne_fft_3d_force_diagnostic_cpp <- function(indices, distances, layout, perplexity, exaggeration, grid_size, n_threads) {
    .Call(`_fastEmbedR_tsne_fft_3d_force_diagnostic_cpp`, indices, distances, layout, perplexity, exaggeration, grid_size, n_threads)
}

tsne_auto_parameters_cpp <- function(n, k, perplexity, perplexity_missing, backend, negative_gradient_method) {
    .Call(`_fastEmbedR_tsne_auto_parameters_cpp`, n, k, perplexity, perplexity_missing, backend, negative_gradient_method)
}

knn_tsne_opentsne_float_cpp <- function(indices, distances, y_init, init, n_components, perplexity, theta, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, n_threads, seed, verbose, record_costs, auto_config, auto_iter_end) {
    .Call(`_fastEmbedR_knn_tsne_opentsne_float_cpp`, indices, distances, y_init, init, n_components, perplexity, theta, early_exaggeration_iter, n_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, negative_gradient_method, n_threads, seed, verbose, record_costs, auto_config, auto_iter_end)
}

massive_tsne_optimize_cpp <- function(offsets_path, indices_path, weights_path, access, init_path, output_path, n, dims, early_iter, normal_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, n_threads, start_iter = 0L, state_path = "", checkpoint_every = 0L, checkpoint_callback = NULL) {
    .Call(`_fastEmbedR_massive_tsne_optimize_cpp`, offsets_path, indices_path, weights_path, access, init_path, output_path, n, dims, early_iter, normal_iter, early_exaggeration, exaggeration, learning_rate, learning_rate_auto, initial_momentum, final_momentum, min_gain, max_step_norm, n_threads, start_iter, state_path, checkpoint_every, checkpoint_callback)
}

transform_tsne_cpp <- function(reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, n_threads, seed, verbose) {
    .Call(`_fastEmbedR_transform_tsne_cpp`, reference_layout, indices, distances, y_init, init, initialization, perplexity, n_iter, early_exaggeration_iter, learning_rate, early_exaggeration, exaggeration, initial_momentum, final_momentum, max_grad_norm, max_step_norm, n_negatives, exact_repulsion_threshold, n_threads, seed, verbose)
}

fastembedr_walktrap_cpp <- function(from, to, weight, n_vertices, steps = 4L) {
    .Call(`_fastEmbedR_fastembedr_walktrap_cpp`, from, to, weight, n_vertices, steps)
}

